[[headers]]
for = "/*"

[headers.values]
Cross-Origin-Opener-Policy = "same-origin"
Cross-Origin-Embedder-Policy = "require-corp"
Cross-Origin-Embedder-Policy = "credentialless"
Content-Security-Policy = "frame-ancestors 'self' *.facebook.com *.internalfb.com *.fbcdn.net;" 
