[[headers]]
for = "/*"

[headers.values]
Access-Control-Allow-Origin = "*"
Cross-Origin-Opener-Policy = "same-origin"
Cross-Origin-Embedder-Policy = "require-corp"
Content-Security-Policy = "frame-ancestors 'self' *.facebook.com *.internalfb.com *.fbcdn.net;" 
